// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
	"uuid"
)

const TableNameHospital = "hospitals"

// Hospital mapped from table <hospitals>
type Hospital struct {
	ID         *uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:uuid_generate_v4()" json:"id"`
	Code       *string    `gorm:"column:code;type:character varying(50);not null" json:"code"`
	Name       *string    `gorm:"column:name;type:character varying(100);not null" json:"name"`
	APIBaseURL *string    `gorm:"column:api_base_url;type:text;not null" json:"api_base_url"`
	CreatedAt  *time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt  *time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName Hospital's table name
func (*Hospital) TableName() string {
	return TableNameHospital
}
