// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNamePatient = "patients"

// Patient mapped from table <patients>
type Patient struct {
	ID           *uuid.UUID     `gorm:"column:id;type:uuid;primaryKey;default:uuid_generate_v4()" json:"id"`
	HospitalID   *uuid.UUID     `gorm:"column:hospital_id;type:uuid;not null;uniqueIndex:patients_hospital_id_national_id_idx,priority:1;uniqueIndex:patients_hospital_id_passport_id_idx,priority:1;uniqueIndex:patients_hospital_id_patient_hn_idx,priority:1" json:"hospital_id"`
	NationalID   *string        `gorm:"column:national_id;type:character varying(13);uniqueIndex:patients_hospital_id_national_id_idx,priority:2" json:"national_id"`
	PassportID   *string        `gorm:"column:passport_id;type:character varying(9);uniqueIndex:patients_hospital_id_passport_id_idx,priority:2" json:"passport_id"`
	PatientHn    *string        `gorm:"column:patient_hn;type:character varying(20);uniqueIndex:patients_hospital_id_patient_hn_idx,priority:2" json:"patient_hn"`
	FirstnameTh  *string        `gorm:"column:firstname_th;type:character varying(100)" json:"firstname_th"`
	MiddlenameTh *string        `gorm:"column:middlename_th;type:character varying(100)" json:"middlename_th"`
	LastnameTh   *string        `gorm:"column:lastname_th;type:character varying(100)" json:"lastname_th"`
	FirstnameEn  *string        `gorm:"column:firstname_en;type:character varying(100)" json:"firstname_en"`
	MiddlenameEn *string        `gorm:"column:middlename_en;type:character varying(100)" json:"middlename_en"`
	LastnameEn   *string        `gorm:"column:lastname_en;type:character varying(100)" json:"lastname_en"`
	DateOfBirth  *time.Time     `gorm:"column:date_of_birth;type:date" json:"date_of_birth"`
	PhoneNumber  *string        `gorm:"column:phone_number;type:character varying(10)" json:"phone_number"`
	Email        *string        `gorm:"column:email;type:character varying(100)" json:"email"`
	Gender       *string        `gorm:"column:gender;type:character varying(1)" json:"gender"`
	CreatedAt    *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName Patient's table name
func (*Patient) TableName() string {
	return TableNamePatient
}
