// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

const TableNameStaff = "staffs"

// Staff mapped from table <staffs>
type Staff struct {
	ID             *uuid.UUID     `gorm:"column:id;type:uuid;primaryKey;default:uuid_generate_v4()" json:"id"`
	HospitalID     *uuid.UUID     `gorm:"column:hospital_id;type:uuid;not null;uniqueIndex:staffs_hospital_id_username_idx,priority:1" json:"hospital_id"`
	Username       *string        `gorm:"column:username;type:character varying(100);not null;uniqueIndex:staffs_hospital_id_username_idx,priority:2" json:"username"`
	PasswordHashed *string        `gorm:"column:password_hashed;type:character varying(128);not null" json:"password_hashed"`
	Firstname      *string        `gorm:"column:firstname;type:character varying(100)" json:"firstname"`
	Midname        *string        `gorm:"column:midname;type:character varying(100)" json:"midname"`
	Lastname       *string        `gorm:"column:lastname;type:character varying(100)" json:"lastname"`
	Email          *string        `gorm:"column:email;type:character varying(100)" json:"email"`
	CreatedAt      *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt      *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	LastLoginAt    *time.Time     `gorm:"column:last_login_at;type:timestamp with time zone" json:"last_login_at"`
}

// TableName Staff's table name
func (*Staff) TableName() string {
	return TableNameStaff
}
